name: gymm_ai_landing_page
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_inset_shadow: ^2.0.3
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  video_player: ^2.10.1
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_analytics: ^12.0.0
  url_launcher: ^6.3.2
  flutter_screenutil: ^5.9.3
  ai_glow: ^0.0.2
  flutter_markdown: ^0.6.18
  go_router: ^17.0.0
  google_fonts: ^6.1.0
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/png/

  fonts:
    - family: Suisse
      fonts:
        - asset: assets/fonts/suisse_medium.ttf
