name: gymm_ai_landing_page
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_inset_shadow: ^2.0.3
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  video_player: ^2.10.0
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_analytics: ^12.0.0
  url_launcher: ^6.3.2
  flutter_screenutil: ^5.9.3
  ai_glow: ^0.0.2
  flutter_markdown: ^0.6.18
  go_router: ^17.0.0
  google_fonts: ^6.1.0
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/png/
    - assets/ellipses/


  fonts:
    - family: Suisse
      fonts:
        - asset: assets/fonts/suisse_medium.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_18pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter_18pt-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/inter/Inter_18pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter_18pt-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/inter/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter_18pt-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/inter/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter_18pt-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/inter/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_18pt-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_18pt-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/inter/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter_18pt-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/inter/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter_18pt-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/inter/Inter_18pt-Black.ttf
          weight: 900
        - asset: assets/fonts/inter/Inter_18pt-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/inter/Inter_24pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter_24pt-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/inter/Inter_24pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter_24pt-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/inter/Inter_24pt-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter_24pt-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/inter/Inter_24pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter_24pt-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/inter/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_24pt-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/inter/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_24pt-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/inter/Inter_24pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter_24pt-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/inter/Inter_24pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter_24pt-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/inter/Inter_24pt-Black.ttf
          weight: 900
        - asset: assets/fonts/inter/Inter_24pt-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/inter/Inter_28pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter_28pt-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/inter/Inter_28pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter_28pt-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/inter/Inter_28pt-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter_28pt-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/inter/Inter_28pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter_28pt-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/inter/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_28pt-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/inter/Inter_28pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_28pt-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/inter/Inter_28pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter_28pt-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/inter/Inter_28pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter_28pt-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/inter/Inter_28pt-Black.ttf
          weight: 900
        - asset: assets/fonts/inter/Inter_28pt-BlackItalic.ttf
          weight: 900
          style: italic
